image: 123marvin123/typst:0.3.0

stages:
  - build
  - release

variables:
  # Evita problemas de caching de repositorio ? Todavia es tuvil ????
  GIT_SUBMODULE_STRATEGY: recursive

build_pdf:
  stage: build
  script:
    # Compila reporte.typ -> reporte.pdf
    - typst compile reporte.typ reporte.pdf
  artifacts:
    name: "reporte-${CI_COMMIT_SHORT_SHA}"
    when: always
    expire_in: 1 week
    paths:
      - reporte.pdf

release_pdf:
  stage: release
  # Se ejecuta con tags gps --tag
  only:
    - tags
  needs:
    - job: build_pdf
      artifacts: true
  release:
    name: "Release ${CI_COMMIT_TAG}"
    tag_name: "${CI_COMMIT_TAG}"
    description: |
      Versión automática generada por CI/CD.
      - PDF: reporte.pdf
    assets:
      links:
        - name: "Descargar reporte.pdf"
          url: "${CI_PROJECT_URL}/-/jobs/${CI_JOB_ID}/artifacts/raw/reporte.pdf"
