image: 123marvin123/typst:0.3.0

stages:
  - build
  - deploy

compile_typst:
    stage: build
    script:
        - typst -v compile report.typ
    artifacts:
        when: always
        paths:
            - ./*.pdf # send to a mail or as a release ????!?!

pages:
    stage: deploy
    script:
        - mkdir .public
        - cp -r ./* .public
        - rm -rf public
        - mv .public public
    artifacts:
        paths:
        - public
    rules:
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
